[project]
name = "odoo-addons-sygel-technology-sy-crm"
version = "18.0.20251003.2"
dependencies = [
    "odoo-addon-crm_group_sale_salesman_extension==18.0.*",
    "odoo-addon-crm_sale_automatic_quotation==18.0.*",
    "odoo-addon-salesperson_transfer_portfolio==18.0.*",
]
classifiers=[
    "Programming Language :: Python",
    "Framework :: Odoo",
    "Framework :: Odoo :: 18.0",
]
